Repository sansan-event-fusion/spark-2023-teamS, pull requests merged in 2023-09, with the labels that each got.

#16 バックエンド・Docker開発環境の構築
  server/.env.example
  server/README.md
  server/composer.json
  server/composer.lock
  server/docker-compose.yml
  server/phpunit.xml
Labels: backend

#17 購入者登録APIの構築
  server/app/Http/Controllers/Api/UserController.php
  server/app/Http/Requests/StoreUserRequest.php
  server/app/Http/Resources/UserResource.php
  server/app/Models/User.php
  server/app/Models/UserOld.php
  server/database/migrations/2023_09_10_073422_create_users_table.php
  server/database/seeders/DatabaseSeeder.php
  server/database/seeders/UserSeeder.php
  server/docker-compose.yml
  server/docker/8.2/Dockerfile
  server/docker/8.2/php.ini
  server/docker/8.2/start-container
  server/docker/8.2/supervisord.conf
  server/docker/mysql/create-testing-database.sh
  server/docker/pgsql/create-testing-database.sql
  server/routes/api.php
Labels: backend

#19 agentsテーブルとbuyersテーブルに関わるマイグレーションの作成
  server/app/Http/Controllers/Api/BuyerController.php
  server/app/Http/Controllers/Api/UserController.php
  server/app/Http/Requests/StoreBuyerRequest.php
  server/app/Http/Resources/BuyerResource.php
  server/app/Models/Buyer.php
  server/database/migrations/2023_09_10_124039_create_buyers_table.php
  server/database/migrations/2023_09_10_125858_create_agents_table.php
  server/database/seeders/AgentSeeder.php
  server/database/seeders/BuyerSeeder.php
  server/database/seeders/DatabaseSeeder.php
  server/routes/api.php
Labels: backend

#20 histries, evaluations, shiftsテーブルの作成。
  server/app/Models/Buyer.php
  server/database/migrations/2023_09_11_010747_create_histories_table.php
  server/database/migrations/2023_09_11_015101_create_evaluations_table.php
  server/database/migrations/2023_09_11_021110_create_shifts_table.php
  server/database/seeders/DatabaseSeeder.php
  server/database/seeders/EvaluationSeeder.php
  server/database/seeders/HistorySeeder.php
  server/database/seeders/ShiftSeeder.php
Labels: backend

#30 配送登録のAPI実装
  server/app/Http/Controllers/Api/HistoryController.php
  server/app/Http/Requests/StoreHistoryRequest.php
  server/app/Http/Resources/HistoryResource.php
  server/app/Models/History.php
  server/database/migrations/2023_09_11_105448_set_default_value_for_status_in_histories_table.php
  server/routes/api.php
Labels: backend

#36 配送完了API（PATCH）の作成
  server/app/Http/Controllers/Api/HistoryController.php
  server/routes/api.php
Labels: backend

#32 【UI】ユーザー登録画面の作成
  client/public/images/logo.png
  client/src/pages/signup/index.tsx
Labels: frontend

#28 【UI】購入者のスタートページ作成
  client/src/components/Header/index.tsx
  client/src/pages/buyer/start/index.tsx
Labels: frontend

#39 【UI】代理人のスケジュール画面作成
  client/src/components/AddShiftDialog/index.tsx
  client/src/components/AddShiftDialog/types.ts
  client/src/components/DailyUserCountCard/index.tsx
  client/src/components/DeliveryScheduleList/index.tsx
  client/src/components/DeliveryShiftList/index.tsx
  client/src/components/UserCountList/index.tsx
  client/src/pages/agent/schedule/index.tsx
Labels: frontend

#61 Frontend/feature/payment page
  client/src/components/AxiosProvider/index.tsx
  client/src/components/Header/index.tsx
  client/src/components/PaymentCard/index.tsx
  client/src/components/RequestDetailsCard/index.tsx
  client/src/pages/buyer/request/index.tsx
Labels: bug
